#pragma once

#include "pluginterfaces/base/fplatform.h"
#include "projectversion.h" // generated by CMake

#define stringPluginName        "Kangaroo"
#define stringOriginalFilename	"Kangaroo.vst3"

#if SMTG_PLATFORM_64
#define stringFileDescription	"Kangaroo VST3-SDK (64Bit)"
#else
#define stringFileDescription	"Kangaroo VST3-SDK"
#endif

#define stringCompanyWeb		"https://www.digorydoo.ch"
#define stringCompanyEmail		"mailto:no-reply@digorydoo.ch"
#define stringCompanyName		"Digory Doolittle"
#define stringLegalCopyright	"© 2022 Digory Doolittle"
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
